### earn points
POST http://localhost:8080/points/earn?sessionId=2345-6789-1234&amount=100

### start game session
POST http://localhost:8080/games/start?sessionId=4567-6789-1234

### find all game sessions
GET http://localhost:8080/games/all

### find game session
GET http://localhost:8080/games/2345-6789-1234
